# This file was generated by GoReleaser. DO NOT EDIT.
class AwsCct < Formula
  desc "AWS Cost Comparison Tool"
  homepage "https://github.com/rocketmiles/aws-cct"
  version "0.3.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rocketmiles/aws-cct/releases/download/v0.3.1/aws-cct_0.3.1_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
    sha256 "f5f8b540595d54eb79f718c6fa3747d05bd035ea5e8f60c2e87fa474acd15ac2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rocketmiles/aws-cct/releases/download/v0.3.1/aws-cct_0.3.1_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "310c0d989852f61f05e8e9458c5278a48cb613009cc482d5a2ac103492cb431c"
    end
  end

  def install
    bin.install "aws-cct"
  end

  test do
    system "#{bin}/aws-cct --help"
  end
end
